# backend/pdf_export.py
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import io
import os

def generate_pdf_report(analysis_data: dict, repo_url: str):
    """Generate PDF report for repository analysis"""
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#238636'),
        spaceAfter=30
    )
    
    # Title
    story.append(Paragraph(f"CodeSnap AI Report: {analysis_data.get('full_name', 'Repository')}", title_style))
    story.append(Spacer(1, 12))
    
    # Basic Info
    story.append(Paragraph("Repository Information", styles['Heading2']))
    story.append(Spacer(1, 6))
    
    info_data = [
        ["Repository:", analysis_data.get('full_name', 'N/A')],
        ["Description:", analysis_data.get('description', 'No description')[:200]],
        ["Stars:", str(analysis_data.get('stars', 0))],
        ["Forks:", str(analysis_data.get('forks', 0))],
        ["Open Issues:", str(analysis_data.get('open_issues', 0))],
        ["Primary Language:", analysis_data.get('language', 'Unknown')],
        ["License:", analysis_data.get('license', 'No license')],
        ["Created:", analysis_data.get('created_at', 'Unknown')],
        ["Last Updated:", analysis_data.get('updated_at', 'Unknown')],
    ]
    
    table = Table(info_data, colWidths=[1.5*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    story.append(table)
    story.append(Spacer(1, 20))
    
    # Architecture
    story.append(Paragraph("Architecture", styles['Heading2']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Pattern: {analysis_data.get('architecture_pattern', 'Standard')}", styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Tech Stack
    story.append(Paragraph("Technology Stack", styles['Heading2']))
    story.append(Spacer(1, 6))
    tech_stack = analysis_data.get('tech_stack', [])
    tech_text = ", ".join(tech_stack) if tech_stack else "Not detected"
    story.append(Paragraph(tech_text, styles['Normal']))
    story.append(Spacer(1, 20))
    
    # URL
    story.append(Paragraph("Repository URL", styles['Heading2']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<link href='{repo_url}'>{repo_url}</link>", styles['Normal']))
    story.append(Spacer(1, 30))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        alignment=1
    )
    story.append(Paragraph(f"Generated by CodeSnap AI Pro on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))
    story.append(Paragraph(f"Powered by GitHub API & AI Analysis", footer_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer

from datetime import datetime